-obfuscationdictionary obfuscation.txt
-classobfuscationdictionary obfuscation.txt
-packageobfuscationdictionary obfuscation.txt
-keepattributes SourceFile, !LineNumberTable, !Signature, !Exceptions, !InnerClasses, !EnclosingMethod
-renamesourcefileattribute BotX
-dontshrink