-dontpreverify
-repackageclasses "IIII"
-dontshrink
-dontskipnonpubliclibraryclasses
-allowaccessmodification
-obfuscationdictionary obfuscation.txt
-classobfuscationdictionary obfuscation.txt
-packageobfuscationdictionary obfuscation.txt
-keepattributes SourceFile, *Annotation*
-renamesourcefileattribute BotX